# Generated by Django 5.0.3 on 2024-04-04 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='InfluencersTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content_category', models.CharField(max_length=50)),
                ('average_views', models.IntegerField()),
                ('average_engagement', models.IntegerField()),
                ('average_likes', models.IntegerField()),
                ('subscribers_count', models.IntegerField()),
                ('last_update', models.DateTimeField()),
                ('youtube_url', models.URLField(unique=True)),
                ('facebook_url', models.URLField(unique=True)),
                ('instagram_url', models.URLField(unique=True)),
                ('tiktok_url', models.URLField(unique=True)),
                ('twitter_url', models.URLField(unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='SponsorsTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=50)),
                ('content_category', models.CharField(max_length=50)),
                ('company_website', models.URLField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='UsersTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=70)),
                ('email', models.EmailField(max_length=70)),
                ('phone_number', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=60)),
                ('account_type', models.CharField(max_length=50)),
                ('profile_picture', models.BinaryField(blank=True, null=True)),
                ('bio_description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='FacebookTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField(unique=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baseApplication.influencerstbl')),
            ],
        ),
        migrations.CreateModel(
            name='InstagramTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField(unique=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baseApplication.influencerstbl')),
            ],
        ),
        migrations.CreateModel(
            name='TiktokTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField(unique=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baseApplication.influencerstbl')),
            ],
        ),
        migrations.CreateModel(
            name='TwitterTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField(unique=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baseApplication.influencerstbl')),
            ],
        ),
        migrations.CreateModel(
            name='MessagingTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_content', models.TextField()),
                ('message_time', models.DateTimeField()),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to='baseApplication.userstbl')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to='baseApplication.userstbl')),
            ],
        ),
        migrations.CreateModel(
            name='AdminsTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(max_length=50)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='baseApplication.userstbl')),
            ],
        ),
        migrations.CreateModel(
            name='YouTubeTBL',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_url', models.URLField(unique=True)),
                ('influencer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='baseApplication.influencerstbl')),
            ],
        ),
    ]
