# Generated by Django 5.0.2 on 2024-04-07 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0003_userstbl_last_login'),
    ]

    operations = [
        migrations.AddField(
            model_name='userstbl',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='userstbl',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='email',
            field=models.EmailField(max_length=70, unique=True),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
        migrations.AlterField(
            model_name='userstbl',
            name='username',
            field=models.CharField(max_length=70, unique=True),
        ),
    ]
