# Generated by Django 5.0.3 on 2024-06-24 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('baseApplication', '0006_alter_room_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='accepted',
            field=models.BooleanField(default=True),
        ),
    ]
